# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: -∞ | singularity | +∞
email: zgfyou@163.com
description: > # this means to ignore newlines until "baseurl:"
  I am a new learner of Jekyll. Try to make some fun with it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.nietzsche.wang" # the base hostname & protocol for your site
twitter_username: zgfyou
github_username:  codeaten

# Build settings
markdown: kramdown
